# 自动生成：上海图书馆开放数据 webapi 接口注册表（源自 api_2025.txt）
# id, method, path(含{0}{1}路径占位), params(查询参数), path_params, family, needs_key
ENDPOINTS = [
    {"id": "pdf_list", "method": "POST", "path": "https://data1.library.sh.cn/service_pdf_race/race/pdf/list", "params": [], "path_params": [], "family": "竞赛PDF文献", "needs_key": True},
    {"id": "pdf_info", "method": "POST", "path": "https://data1.library.sh.cn/service_pdf_race/race/pdf/info", "params": [], "path_params": [], "family": "竞赛PDF文献", "needs_key": True},
    {"id": "pdf_stream", "method": "POST", "path": "https://data1.library.sh.cn/service_pdf_race/race/pdf/stream", "params": [], "path_params": [], "family": "竞赛PDF文献", "needs_key": True},
    {"id": "zoutaofen_getOrgYearListInterface", "method": "GET", "path": "https://data1.library.sh.cn/webapi/zoutaofen/getOrgYearListInterface", "params": [], "path_params": [], "family": "韬奋纪念馆", "needs_key": True},
    {"id": "zoutaofen_getHumanYearListInterface", "method": "GET", "path": "https://data1.library.sh.cn/webapi/zoutaofen/getHumanYearListInterface", "params": [], "path_params": [], "family": "韬奋纪念馆", "needs_key": True},
    {"id": "zoutaofen_getBookInterface", "method": "GET", "path": "https://data1.library.sh.cn/webapi/zoutaofen/getBookInterface", "params": [], "path_params": [], "family": "韬奋纪念馆", "needs_key": True},
    {"id": "zoutaofen_getRelationInterFace", "method": "GET", "path": "https://data1.library.sh.cn/webapi/zoutaofen/getRelationInterFace", "params": [], "path_params": [], "family": "韬奋纪念馆", "needs_key": True},
    {"id": "beitie_search", "method": "POST", "path": "https://data1.library.sh.cn/webapi/beitie/search", "params": [], "path_params": [], "family": "其他", "needs_key": True},
    {"id": "beitie_info", "method": "GET", "path": "https://data1.library.sh.cn/webapi/beitie/info", "params": ["uri"], "path_params": [], "family": "其他", "needs_key": True},
    {"id": "danzi_search", "method": "POST", "path": "https://data1.library.sh.cn/webapi/beitie/danzi/search", "params": [], "path_params": [], "family": "其他", "needs_key": True},
    {"id": "beitie_background", "method": "GET", "path": "https://data1.library.sh.cn/webapi/beitie/beitie/background", "params": ["pagesize"], "path_params": [], "family": "其他", "needs_key": True},
    {"id": "person_search", "method": "GET", "path": "https://data1.library.sh.cn/webapi/beitie/person/search", "params": ["firstchar", "nativeprov"], "path_params": [], "family": "其他", "needs_key": True},
    {"id": "person_info", "method": "GET", "path": "https://data1.library.sh.cn/webapi/beitie/person/info", "params": ["uri"], "path_params": [], "family": "其他", "needs_key": True},
    {"id": "person_work", "method": "GET", "path": "https://data1.library.sh.cn/webapi/beitie/person/work", "params": ["uri"], "path_params": [], "family": "其他", "needs_key": True},
    {"id": "kg_list", "method": "GET", "path": "https://data1.library.sh.cn/webapi/kg/list", "params": ["freetext", "pagenum"], "path_params": [], "family": "知识图谱人物", "needs_key": True},
    {"id": "kg_detail", "method": "GET", "path": "https://data1.library.sh.cn/webapi/kg/detail", "params": ["personuri"], "path_params": [], "family": "知识图谱人物", "needs_key": True},
    {"id": "org_list", "method": "GET", "path": "https://data1.library.sh.cn/shnh/whzk/webapi/org/list", "params": ["freetext"], "path_params": [], "family": "文化总库机构", "needs_key": True},
    {"id": "org_detail", "method": "GET", "path": "https://data1.library.sh.cn/shnh/whzk/webapi/org/detail", "params": ["uri"], "path_params": [], "family": "文化总库机构", "needs_key": True},
    {"id": "yutu_list", "method": "GET", "path": "https://data1.library.sh.cn/webapi/yutu/list", "params": ["freetext", "pagenum"], "path_params": [], "family": "舆图", "needs_key": True},
    {"id": "yutu_detail", "method": "GET", "path": "https://data1.library.sh.cn/webapi/yutu/detail", "params": ["instanceuri"], "path_params": [], "family": "舆图", "needs_key": True},
    {"id": "shouji_list", "method": "GET", "path": "https://data1.library.sh.cn/webapi/shouji/list", "params": ["creator", "freetext", "personuri"], "path_params": [], "family": "手迹", "needs_key": True},
    {"id": "shouji_detail", "method": "GET", "path": "https://data1.library.sh.cn/webapi/shouji/detail", "params": ["uri"], "path_params": [], "family": "手迹", "needs_key": True},
    {"id": "architecture_getArchitectures", "method": "GET", "path": "https://data1.library.sh.cn/shnh/gmwx/webapi/architecture/getArchitectures", "params": [], "path_params": [], "family": "国漫革命文献", "needs_key": True},
    {"id": "architecture_getArchitectureDetail", "method": "GET", "path": "https://data1.library.sh.cn/shnh/gmwx/webapi/architecture/getArchitectureDetail", "params": [], "path_params": [], "family": "国漫革命文献", "needs_key": True},
    {"id": "work_list", "method": "GET", "path": "https://data1.library.sh.cn/bib/webapi/work/list", "params": ["freetext", "title"], "path_params": [], "family": "书目数据", "needs_key": True},
    {"id": "work_detail", "method": "GET", "path": "https://data1.library.sh.cn/bib/webapi/work/detail", "params": ["uri"], "path_params": [], "family": "书目数据", "needs_key": True},
    {"id": "instance_list", "method": "GET", "path": "https://data1.library.sh.cn/bib/webapi/instance/list", "params": ["freetext", "title"], "path_params": [], "family": "书目数据", "needs_key": True},
    {"id": "instance_detail", "method": "GET", "path": "https://data1.library.sh.cn/bib/webapi/instance/detail", "params": ["uri"], "path_params": [], "family": "书目数据", "needs_key": True},
    {"id": "route_getEventList", "method": "GET", "path": "https://data1.library.sh.cn/webapi/hsly/route/getEventList", "params": ["eventdate", "eventfreetext"], "path_params": [], "family": "红色旅游事件", "needs_key": True},
    {"id": "route_getEventDetail", "method": "GET", "path": "https://data1.library.sh.cn/webapi/hsly/route/getEventDetail", "params": ["uri"], "path_params": [], "family": "红色旅游事件", "needs_key": True},
    {"id": "geonames_list", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dmz/webapi/geonames/list", "params": ["freetext", "type"], "path_params": [], "family": "地名志", "needs_key": True},
    {"id": "geonames_detail", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dmz/webapi/geonames/detail", "params": ["uri"], "path_params": [], "family": "地名志", "needs_key": True},
    {"id": "road_list", "method": "GET", "path": "https://data1.library.sh.cn/shnh/wkl/webapi/road/list", "params": ["freetext"], "path_params": [], "family": "武康路历史", "needs_key": True},
    {"id": "building_list", "method": "GET", "path": "https://data1.library.sh.cn/shnh/wkl/webapi/building/list", "params": ["freetext"], "path_params": [], "family": "武康路历史", "needs_key": True},
    {"id": "event_list", "method": "GET", "path": "https://data1.library.sh.cn/shnh/wkl/webapi/building/event/list", "params": ["buri"], "path_params": [], "family": "武康路历史", "needs_key": True},
    {"id": "building_detail", "method": "GET", "path": "https://data1.library.sh.cn/shnh/wkl/webapi/building/detail", "params": ["uri"], "path_params": [], "family": "武康路历史", "needs_key": True},
    {"id": "road_detail", "method": "GET", "path": "https://data1.library.sh.cn/shnh/wkl/webapi/road/detail", "params": ["uri"], "path_params": [], "family": "武康路历史", "needs_key": True},
    {"id": "persons_detail", "method": "GET", "path": "https://data1.library.sh.cn/shnh/wkl/webapi/persons/detail", "params": ["uri"], "path_params": [], "family": "武康路历史", "needs_key": True},
    {"id": "persons_list", "method": "GET", "path": "https://data1.library.sh.cn/shnh/wkl/webapi/persons/list", "params": ["pname"], "path_params": [], "family": "武康路历史", "needs_key": True},
    {"id": "movie_getMovie", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dydata/webapi/movie/getMovie", "params": ["video"], "path_params": [], "family": "近代城市文化", "needs_key": True},
    {"id": "movie_movieDetail", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dydata/webapi/movie/movieDetail", "params": ["uri"], "path_params": [], "family": "近代城市文化", "needs_key": True},
    {"id": "video_videoDetail", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dydata/webapi/video/videoDetail", "params": ["uri"], "path_params": [], "family": "近代城市文化", "needs_key": True},
    {"id": "photo_photoDetail", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dydata/webapi/photo/photoDetail", "params": ["uri"], "path_params": [], "family": "近代城市文化", "needs_key": True},
    {"id": "photo_getPhotoList", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dydata/webapi/photo/getPhotoList", "params": ["freetext", "type"], "path_params": [], "family": "近代城市文化", "needs_key": True},
    {"id": "music_musicDetail", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dydata/webapi/music/musicDetail", "params": ["uri"], "path_params": [], "family": "近代城市文化", "needs_key": True},
    {"id": "music_getMusicList", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dydata/webapi/music/getMusicList", "params": ["freetext", "name"], "path_params": [], "family": "近代城市文化", "needs_key": True},
    {"id": "magazine_getMagazineList", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dydata/webapi/magazine/getMagazineList", "params": ["foafname", "freetext"], "path_params": [], "family": "近代城市文化", "needs_key": True},
    {"id": "magazine_magazineDetail", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dydata/webapi/magazine/magazineDetail", "params": ["uri"], "path_params": [], "family": "近代城市文化", "needs_key": True},
    {"id": "artical_getArticalList", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dydata/webapi/artical/getArticalList", "params": ["freetext", "title"], "path_params": [], "family": "近代城市文化", "needs_key": True},
    {"id": "picture_getPictureList", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dydata/webapi/picture/getPictureList", "params": ["freetext", "name"], "path_params": [], "family": "近代城市文化", "needs_key": True},
    {"id": "magazine_getPzYearOfMag", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dydata/webapi/magazine/getPzYearOfMag", "params": ["uri"], "path_params": [], "family": "近代城市文化", "needs_key": True},
    {"id": "magazine_getPzJuanqiOfMag", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dydata/webapi/magazine/getPzJuanqiOfMag", "params": ["uri", "year"], "path_params": [], "family": "近代城市文化", "needs_key": True},
    {"id": "magazine_getPzListOfMag", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dydata/webapi/magazine/getPzListOfMag", "params": ["juanqi"], "path_params": [], "family": "近代城市文化", "needs_key": True},
    {"id": "architecture_architectureDetail", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dydata/webapi/architecture/architectureDetail", "params": ["uri"], "path_params": [], "family": "近代城市文化", "needs_key": True},
    {"id": "person_personDetailAll", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dydata/webapi/person/personDetailAll", "params": ["uri"], "path_params": [], "family": "近代城市文化", "needs_key": True},
    {"id": "movie_getAutoComList", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dydata/webapi/movie/getAutoComList", "params": ["graph"], "path_params": [], "family": "近代城市文化", "needs_key": True},
    {"id": "video_getVideoList", "method": "POST", "path": "https://data1.library.sh.cn/shnh/dydata/webapi/video/getVideoList", "params": ["title"], "path_params": [], "family": "近代城市文化", "needs_key": True},
    {"id": "movie_getHomeFilmBillList", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dydata/webapi/movie/getHomeFilmBillList", "params": [], "path_params": [], "family": "近代城市文化", "needs_key": True},
    {"id": "architecture_getArchitecture", "method": "GET", "path": "https://data1.library.sh.cn/shnh/dydata/webapi/architecture/getArchitecture", "params": ["freetext"], "path_params": [], "family": "近代城市文化", "needs_key": True},
    {"id": "instance_search", "method": "GET", "path": "https://data1.library.sh.cn/shnh/gmwx/webapi/instance/search", "params": ["freetext", "title"], "path_params": [], "family": "国漫革命文献", "needs_key": True},
    {"id": "instance_detail_1", "method": "GET", "path": "https://data1.library.sh.cn/shnh/gmwx/webapi/instance/detail", "params": ["uri"], "path_params": [], "family": "国漫革命文献", "needs_key": True},
    {"id": "work_search", "method": "GET", "path": "https://data1.library.sh.cn/shnh/gmwx/webapi/work/search", "params": ["freetext", "title"], "path_params": [], "family": "国漫革命文献", "needs_key": True},
    {"id": "work_detail_1", "method": "GET", "path": "https://data1.library.sh.cn/shnh/gmwx/webapi/work/detail", "params": ["uri"], "path_params": [], "family": "国漫革命文献", "needs_key": True},
    {"id": "instance_placeInArea", "method": "GET", "path": "https://data1.library.sh.cn/shnh/gmwx/webapi//instance/placeInArea", "params": ["points"], "path_params": [], "family": "国漫革命文献", "needs_key": True},
    {"id": "webapi_instances", "method": "GET", "path": "https://data1.library.sh.cn/gj/webapi/instances", "params": ["freetext"], "path_params": [], "family": "古籍循证", "needs_key": True},
    {"id": "webapi_instanceInfo", "method": "GET", "path": "https://data1.library.sh.cn/gj/webapi/instanceInfo", "params": ["uri"], "path_params": [], "family": "古籍循证", "needs_key": True},
    {"id": "webapi_items", "method": "GET", "path": "https://data1.library.sh.cn/gj/webapi/items", "params": ["uri"], "path_params": [], "family": "古籍循证", "needs_key": True},
    {"id": "webapi_works", "method": "GET", "path": "https://data1.library.sh.cn/gj/webapi/works", "params": ["title"], "path_params": [], "family": "古籍循证", "needs_key": True},
    {"id": "webapi_workPersons", "method": "GET", "path": "https://data1.library.sh.cn/gj/webapi/workPersons", "params": ["uri"], "path_params": [], "family": "古籍循证", "needs_key": True},
    {"id": "webapi_workAnnotations", "method": "GET", "path": "https://data1.library.sh.cn/gj/webapi/workAnnotations", "params": ["uri"], "path_params": [], "family": "古籍循证", "needs_key": True},
    {"id": "webapi_workInfo", "method": "GET", "path": "https://data1.library.sh.cn/gj/webapi/workInfo", "params": ["uri"], "path_params": [], "family": "古籍循证", "needs_key": True},
    {"id": "webapi_hzInstances", "method": "GET", "path": "https://data1.library.sh.cn/gj/webapi/hzInstances", "params": ["personuri1"], "path_params": [], "family": "古籍循证", "needs_key": True},
    {"id": "webapi_annotations", "method": "GET", "path": "https://data1.library.sh.cn/gj/webapi/annotations", "params": ["worktitle"], "path_params": [], "family": "古籍循证", "needs_key": True},
    {"id": "webapi_classificationList", "method": "GET", "path": "https://data1.library.sh.cn/gj/webapi/classificationList", "params": ["furi", "isloop", "source"], "path_params": [], "family": "古籍循证", "needs_key": True},
    {"id": "webapi_instancesDisplayInfo", "method": "GET", "path": "https://data1.library.sh.cn/gj/webapi/instancesDisplayInfo", "params": ["uri"], "path_params": [], "family": "古籍循证", "needs_key": True},
    {"id": "webapi_seals", "method": "GET", "path": "https://data1.library.sh.cn/gj/webapi/seals", "params": ["freetext", "ownerofseal", "sealname"], "path_params": [], "family": "古籍循证", "needs_key": True},
    {"id": "webapi_sealDetail", "method": "GET", "path": "https://data1.library.sh.cn/gj/webapi/sealDetail", "params": ["seal_uri", "sealimg"], "path_params": [], "family": "古籍循证", "needs_key": True},
    {"id": "webapi_libliotheca", "method": "GET", "path": "https://data1.library.sh.cn/gj/webapi/libliotheca", "params": ["freetext"], "path_params": [], "family": "古籍循证", "needs_key": True},
    {"id": "webapi_sealOwnerList", "method": "GET", "path": "https://data1.library.sh.cn/gj/webapi/sealOwnerList", "params": ["freetext"], "path_params": [], "family": "古籍循证", "needs_key": True},
    {"id": "jp_familyname", "method": "GET", "path": "https://data1.library.sh.cn/jp/familyname/", "params": [], "path_params": [], "family": "家谱", "needs_key": True},
    {"id": "person_data", "method": "GET", "path": "https://data1.library.sh.cn/jp/person/data", "params": [], "path_params": [], "family": "家谱", "needs_key": True},
    {"id": "work_data", "method": "GET", "path": "https://data1.library.sh.cn/jp/work/data", "params": ["title"], "path_params": [], "family": "家谱", "needs_key": True},
    {"id": "persons_data", "method": "GET", "path": "https://data1.library.sh.cn/persons/data", "params": ["fname", "freetext"], "path_params": [], "family": "人名规范库", "needs_key": True},
    {"id": "data1_library_sh_cn_place", "method": "GET", "path": "https://data1.library.sh.cn/place/{0}", "params": [], "path_params": ["[参数1]"], "family": "地名纪年", "needs_key": True},
    {"id": "place", "method": "GET", "path": "https://data1.library.sh.cn/place/杞县", "params": [], "path_params": [], "family": "地名纪年", "needs_key": True},
    {"id": "place_listPlaces", "method": "GET", "path": "https://data1.library.sh.cn/place/listPlaces", "params": [], "path_params": [], "family": "地名纪年", "needs_key": True},
    {"id": "place_listForeignPlaces", "method": "GET", "path": "https://data1.library.sh.cn/place/listForeignPlaces", "params": [], "path_params": [], "family": "地名纪年", "needs_key": True},
    {"id": "data1_library_sh_cn_data", "method": "GET", "path": "https://data1.library.sh.cn/data/{0}.json", "params": [], "path_params": ["[参数1]"], "family": "纪年表关联数据", "needs_key": True},
    {"id": "data__json", "method": "GET", "path": "https://data1.library.sh.cn/data/明.json", "params": [], "path_params": [], "family": "纪年表关联数据", "needs_key": True},
    {"id": "data__2", "method": "GET", "path": "https://data1.library.sh.cn/data/明洪武2", "params": [], "path_params": [], "family": "纪年表关联数据", "needs_key": True},
    {"id": "data_1369_json", "method": "GET", "path": "https://data1.library.sh.cn/data/1369.json", "params": [], "path_params": [], "family": "纪年表关联数据", "needs_key": True},
    {"id": "data1_library_sh_cn_temporal", "method": "GET", "path": "https://data1.library.sh.cn/temporal/", "params": [], "path_params": [], "family": "纪年", "needs_key": True},
    {"id": "data1_library_sh_cn_temporal_json", "method": "GET", "path": "https://data1.library.sh.cn/temporal.json", "params": [], "path_params": [], "family": "纪年", "needs_key": True},
    {"id": "organization_search", "method": "GET", "path": "https://data1.library.sh.cn/organization/search", "params": ["freetext"], "path_params": [], "family": "机构名录", "needs_key": True},
    {"id": "jp_organization", "method": "GET", "path": "https://data1.library.sh.cn/jp/organization/{0}", "params": [], "path_params": ["[参数1]"], "family": "家谱", "needs_key": True},
    {"id": "data1_library_sh_cn_sparql", "method": "GET", "path": "https://data1.library.sh.cn/sparql", "params": [], "path_params": [], "family": "其他", "needs_key": True},
    {"id": "data_jsonld", "method": "GET", "path": "https://data1.library.sh.cn/data/jsonld", "params": ["uri"], "path_params": [], "family": "纪年表关联数据", "needs_key": True},
]
